apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-show
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vikashkaushik01/showcase.git
    path: /
    targetRevision: HEAD
  destination: 
    name: test
    namespace: default